ProvisionSecond.MVCApplication/Models/ErrorViewModel.cs
using System;

namespace ProvisionSecond.MVCApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProvisionSecond.MVCApplication/Controllers/CurrencyController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProvisionSecond.Business.Repository;
using ProvisionSecond.Core.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProvisionSecond.MVCApplication.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly CurrencyRepo _currencyRepo;
        private readonly IMapper _mapper;

        public CurrencyController(CurrencyRepo currencyRepo, IMapper mapper)
        {
            _currencyRepo = currencyRepo;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var Currencies = _currencyRepo.GetDistinctCurrencies();
            ViewBag.Currencies = Currencies;
            return View();
        }

        [HttpPost]
        public IActionResult GetCurrencyData(string input)
        {
            var data = _currencyRepo
                .Get(Currency => Currency.Code == input)
                .Select(Currency => _mapper.Map<CurrencyGraph>(Currency))
                .ToList();
            return Ok(data);
        }
    }
}

ProvisionSecond.MVCApplication/Controllers/DataController.cs
using AutoMapper;
using CurrencyProvider.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProvisionSecond.Business.Repository;
using ProvisionSecond.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ProvisionSecond.Core.Entities;
using System.Net;

namespace ProvisionSecond.MVCApplication.Controllers
{
    [Route("api/[controller]/[action]")]
    public class DataController : Controller
    {
        //private readonly MyContext _mycontext;
        private readonly CurrencyRepo _currencyRepo;
        private readonly IMapper _mapper;

        public DataController(CurrencyRepo currencyRepo, IMapper mapper)
        {
            //_mycontext = myContext;
            _currencyRepo = currencyRepo;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Save()
        {
            int number = _currencyRepo.CountOfRows();
            if (number != 0)
            {
                _currencyRepo.DeleteAllRows();
            }
            var service = new CurrencyService();
            
            DateTime now = DateTime.UtcNow;
            DateTime olddate = new DateTime(now.Year, now.Month - 2, now.Day);
            for (DateTime date = olddate; now.CompareTo(date) > 0; date = date.AddDays(1.0))
            {
                if (date.DayOfWeek == DayOfWeek.Saturday || date.DayOfWeek == DayOfWeek.Sunday)
                {
                    continue;
                }
                var Response = service.GetCurrencyRates(date);
                foreach (var Currency in Response)
                {
                    var model = _mapper.Map<CurrencyPro>(Currency);
                    model.DateTime = date;
                    _currencyRepo.Insert(model);
                }
            }
            return Redirect("/Currency/Index");
        }
    }
}

ProvisionSecond.MVCApplication/Views/Currency/Index.cshtml
@{
    ViewData["Title"] = "Currency Page";
}
<div id="container">
    <h3>Currency Search</h3>
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Currency Code" aria-label="Currency Code" aria-describedby="basic-addon2" id="inputCurrencyCode">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="myButton">Search</button>
        </div>
    </div>
</div>
<div id="containerbelow">
    <p class="label"></p>
    <div id="myChart"></div>
    @*<svg width="500" height="400"></svg>*@
</div>
@section Scripts
{
    <script>
        var Currencies = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.Currencies));
        if (Currencies.length != 0) {
            $("#myButton").click(function () {
                var input = $("#inputCurrencyCode").val().toUpperCase();
                var inputInCurrencies = Currencies.includes(input);
                if (inputInCurrencies) {
                    var model = {
                        input: input
                    };
                    $.ajax({
                        url: '@Url.Action("GetCurrencyData", "Currency")',
                        type: "POST",
                        data: model,
                        dataType: "json",
                        error: function (request, status, error) {
                            //console.log(request);
                        },
                        //success: function (response) {
                        //    var parseDate = d3.time.format("%Y-%m-%dT%H:%M:%S").parse;
                        //    response.forEach(function (d) {
                        //        d.dateTime = parseDate(d.dateTime);
                        //        d.forexBuying = +d.forexBuying;
                        //    });
                        //    var svg = d3.select("svg"),
                        //        margin = 200,
                        //        width = svg.attr("width") - margin,
                        //        height = svg.attr("height") - margin
                        //    var xScale = d3.scaleLinear().domain([0, 100]).range([0, width]),
                        //        yScale = d3.scaleLinear().domain([0, 200]).range([height, 0]);
                        //}
                        success: function (response) {
                            /*console.log(response);*/
                            $("#myChart").html("");
                            var label = d3.select(".label");
                            // Set the dimensions of the canvas / graph
                            var margin = { top: 30, right: 20, bottom: 30, left: 50 },
                                width = 1000 - margin.left - margin.right,
                                height = 270 - margin.top - margin.bottom;
                            // Parse the date / time
                            var parseDate = d3.time.format("%Y-%m-%dT%H:%M:%S").parse;
                            // Set the ranges
                            var x = d3.time.scale().range([0, width]);
                            var y = d3.scale.linear().range([height, 0]);
                            // Define the axes
                            var xAxis = d3.svg.axis().scale(x)
                                .orient("bottom").ticks(5);
                            var yAxis = d3.svg.axis().scale(y)
                                .orient("left").ticks(5);
                            // Define the line
                            var valueline = d3.svg.line()
                                .x(function (d) { return x(d.dateTime); })
                                .y(function (d) { return y(d.forexBuying); });
                            // Adds the svg canvas
                            var svg = d3.select("#myChart")
                                .append("svg")
                                .attr("width", width + margin.left + margin.right)
                                .attr("height", height + margin.top + margin.bottom)
                                .append("g")
                                .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
                            //
                            response.forEach(function (d) {
                                d.dateTime = parseDate(d.dateTime);
                                /*d.forexBuying = +d.forexBuying;*/
                            });
                            // Scale the range of the data
                            var max = d3.max(response, function (d) { return d.forexBuying; })
                            var min = d3.min(response, function (d) { return d.forexBuying; })
                            var value = ((max + min) * 5) / 200
                            x.domain(d3.extent(response, function (d) { return d.dateTime; }));
                            y.domain([min - value, max + value]);
                            // Add the valueline path.
                            svg.append("path")
                                .attr("class", "line")
                                .attr("d", valueline(response));
                            //
                            svg
                                .selectAll("circle")
                                .data(response)
                                .enter()
                                .append("circle")
                                .attr("r", 8)
                                .attr("cx", function (d) {
                                    return x(d.dateTime)
                                })
                                .attr("cy", function (d) {
                                    return y(d.forexBuying)
                                })
                                .on("mouseover", function (d, i) {
                                    label.style("transform", "translate(" + x(d.dateTime) + "px," + (y(d.forexBuying)) + "px)")
                                    label.text(d.forexBuying)
                                });
                            // Add the X Axis
                            svg.append("g")
                                .attr("class", "x axis")
                                .attr("transform", "translate(0," + height + ")")
                                .call(xAxis);
                            // Add the Y Axis
                            svg.append("g")
                                .attr("class", "y axis")
                                .call(yAxis);
                        }
                    });
                } else {
                    alert("Wrong Input")
                }
            });
        }
        else {
            alert("No data found in the database. Please go '/api/data/save' endpoint for loading data from tcmb to database.")
        }

    </script>
}
@section Styles
{
    <style>
        path {
            stroke: steelblue;
            stroke-width: 2;
            fill: none;
        }
        .axis path,
        .axis line {
            fill: none;
            stroke: grey;
            stroke-width: 1;
            shape-rendering: crispEdges;
        }
        .label {
            position: absolute;
        }
        circle {
            cursor: pointer;
            fill: steelblue;
        }
        #container {
            padding-top: 150px;
            width: 500px;
            margin: auto;
        }
        #containerbelow {
            width: 1000px;
            margin: auto;
        }
    </style>
}

ProvisionSecond.MVCApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProvisionSecond.MVCApplication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    @RenderBody()
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    @*<script src="https://d3js.org/d3.v4.min.js"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>